PLUGINNAME = AJPTechnical

PLUGINOBJECTS = \
MeshWarp.o\
PatchMatchPluginFactory.o PatchMatchPlugin.o PatchMatcher.o\
OffsetMapPluginFactory.o OffsetMapPlugin.o\
TranslateMapPluginFactory.o TranslateMapPlugin.o

SRCDIR = ..

RESOURCES = \
$(SRCDIR)/README.md

include $(SRCDIR)/Makefile.master

VPATH += \
$(SRCDIR)/MeshWarp\
$(SRCDIR)/PatchMatch\
$(SRCDIR)/OffsetMap\
$(SRCDIR)/TranslateMap
